### ISSUE TITLE
Have you done any experiments to prove the performance of the model under ground truth labeling and not GPT4 labeling

### ISSUE THREAD

**Issue by ZiruiSongBest** [baaivision/JudgeLM#11]
Because when I use GPT4 as a judge, It only work when I supply with correct demonstration.

**Comment by Unrealluver** [comment]
Thanks for your interest!

As for the experiments with human judgments, please take a look at Table. 2 in our [paper](https://arxiv.org/abs/2310.17631). We show the zero-shot performance on the PandaLM test set, which summarizes three people reviewer's judgments as one final judgment, i.e., `the 1st answer win`, `the 2nd answer win`, or `tie`. On this benchmark, the JudgeLM's performance even surpasses the GPT-4's.

**Comment by Unrealluver** [comment]
I will close this issue. If there are more questions, you are welcome to raise issues :)

**Comment by NuoJohnChen** [comment]
Could you share the code on calculating the zero-shot performance on the PandaLM test set?
