### ISSUE TITLE
Can you share theminimal `.jsonl` file examples

### ISSUE THREAD

**Issue by deshwalmahesh** [baaivision/JudgeLM#17]
In the [Readme](https://github.com/baaivision/JudgeLM/tree/main/judgelm/llm_judge#step-1-put-llm-generated-results-json-file-in-benchmark-folder-judgelmdatajudgelmanswers-following-the-format-of-judgelmdatajudgelmanswersalpaca_judgelm_valjsonl) there are lot of references given for multiple `.jsonl` files like: 

1.  `./judgelm/data/JudgeLM/answers/alpaca_judgelm_val.jsonl`
2. `./judgelm/data/JudgeLM/judgelm-val-5k-judge-samples.jsonl`.
3. `/share/project/lianghuizhu/JudgeLM-Project/JudgeLM/judgelm/data/JudgeLM/judgelm_val_5k_gpt4.jsonl`
4. `./judgelm/data/MM-Vet/mmvet_predictions.jsonl`

But I could not find those files in the respective directories. Can you please share a minimal examples of how those looks in the directory. I know the data is present at `HF` and there are examples given like:

```
{
  "question_id": 0, 
  "question_body": "My internet service is very expensive...", 
  "decoding_method": "top_p_sampling", 
  "model": "alpaca-native", 
  "text": "There are a few ways to cut down the cost...", 
  "scores": {"logprobs": -7.0179795026779175,...}
}
```

But I'm requesting a one example files on the disk so that I can replicate my respective data exactly.

Thanks in advance.

 @eltociear  @Unrealluver

**Comment by adityamavle** [comment]
If you managed to replicate some examples .jsonl files, could you send the format
