### ISSUE TITLE
hi, how can we use the judge_pair template to judge a single answer.

### ISSUE THREAD

**Issue by eyuansu62** [baaivision/JudgeLM#4]
I am unsure about where to place the score of 10 in the example provided in the paper.

**Comment by LexieeWei** [comment]
the same question

**Comment by LexieeWei** [comment]
the same question，以及后续会新增中文语料吗

**Comment by Unrealluver** [comment]
Greetings!

Thanks for your interest! We have committed the support files, scripts, and document contents. Please refer to the [README](https://github.com/baaivision/JudgeLM/blob/cadd8fbb0910fde6f34356759f2e2be961a57d78/judgelm/llm_judge/README.md?plain=1#L132) for more details.

**Comment by Unrealluver** [comment]
@LexieeWei 感谢您的关注，我们后续会添加中文语料数据。关于中文裁判模型，我们会考虑换用中文支持更好的基础模型。

**Comment by eyuansu62** [comment]
thanks a lot ! and will u release the training data?

**Comment by Unrealluver** [comment]
I will close this issue. If there are more questions, you are welcome to raise issues :)
