### ISSUE TITLE
你好，请教下如何同时给多个答案打分呢？看目前的代码好像还不支持？

### ISSUE THREAD

**Issue by TUNATAKA** [baaivision/JudgeLM#5]

**Comment by Unrealluver** [comment]
Greetings! @TUNATAKA 

Thanks for your interest! We have upload the scripts to grading multi-answers, and corresponding documents at [here](https://github.com/baaivision/JudgeLM/blob/ce12b12779764fe06e28c797cecee86018a298e4/judgelm/llm_judge/README.md?plain=1#L222)

**Comment by Unrealluver** [comment]
I will close this issue. If there are more questions, you are welcome to raise issues :)

**Comment by TUNATAKA** [comment]
> I will close this issue. If there are more questions, you are welcome to raise issues :)

ok,thanks
